### PR TITLE
Fix deprecation warning

### PR DESCRIPTION
**Pull request by Aleksander-Karlsson**
This PR removes deprecated call to `pkg_resources.get_distribution` with `importlib.metadata.version`.

Note: `__name__` = "ecl_data_io.version", so that can't be used without some stringprocessing e.g.
`version(__name__.split(".")[0])`

Pytest-warnings in my project inb4 changing this^
```
pkg_resources\__init__.py:121: DeprecationWarning: pkg_resources is deprecated as an API      
    warnings.warn("pkg_resources is deprecated as an API", DeprecationWarning)

pkg_resources\__init__.py:2870: DeprecationWarning: Deprecated call to `pkg_resources.declare_
namespace('mpl_toolkits')`.
  Implementing implicit namespace packages (as specified in PEP 420) is preferred to `pkg_resources.declare_namespace`. See https://setuptools.pypa.io/en/latest/references/keywords.html#keyword-namespace-packages
    declare_namespace(pkg)

```

### CODE REVIEW

**Comment by eivindjahren** [comment]
Seems to fail with python 3.7, however we are about to drop support for python 3.7 so that should be fine. I'll update the setup with python 3.7 support dropped, and then we can merge this.

**Comment by eivindjahren** [comment]
@Aleksander-Karlsson the tests should pass now if you rebase on master

**Comment by Aleksander-Karlsson** [comment]
Nice 😄 Should be all good now I think!

**Comment by eivindjahren** [comment]
I see your rebase got a bit mangled. I fixed it up, and it should be available here: https://github.com/equinor/ecl-data-io/pull/42 Is it ok if we merge that one?

**Pull request closed without merging**
